name: Demander une VM Debian
description: Crée une VM sur Proxmox via GitHub Actions
labels: [deploy-request]
body:
  - type: input
    id: nom_machine
    attributes:
      label: Nom de la machine (a–z, 0–9, -)
      description: 3–32 caractères, minuscules uniquement
      placeholder: alice
    validations:
      required: true

  - type: textarea
    id: pgp_pub_key
    attributes:
      label: Clé PGP publique
      description: Collez la clé publique ASCII-armored (-----BEGIN PGP PUBLIC KEY BLOCK----- ...)
    validations:
      required: true
